theme: minima
title: Kevin's Blog
author: Kevin Evans
description: This is my little blog about programming, electronics, and whatever I feel like writing about.
header_pages:
  - index.md
  - readings.md
comments: true
disqus:
  shortname: khevans
github_username:  kevinhikaruevans
