name: Post New Blog Post to Mastodon

on:
  push:
    paths:
      - _posts/**

jobs:
  post-to-mastodon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Find new blog post
      id: new_post
      run: |
        LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
        echo "last commit msg='$LAST_COMMIT_MSG'"

        if [[ "$LAST_COMMIT_MSG" == "new post"* ]]; then
          # Get the list of files changed in the latest commit
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          # Find the file in the _posts directory
          NEW_POST=$(echo "$CHANGED_FILES" | grep '^_posts/' | tail -n 1)

          echo "new post=$NEW_POST"

          if [ -n "$NEW_POST" ]; then
            POST_NAME=$(basename "$NEW_POST" .md)
            echo $POST_NAME
            DATE_PART=$(echo "$POST_NAME" | cut -d'-' -f1-3 | tr '-' '/')
            echo $DATE_PART
            SLUG_PART=$(echo "$POST_NAME" | cut -d'-' -f4-)
            echo $SLUG_PART
            POST_URL="https://khevans.com/$DATE_PART/$SLUG_PART/"
            echo $POST_URL
            echo "new_post_url=$POST_URL" >> $GITHUB_ENV
          fi
        fi

    - name: Post to Mastodon
      if: env.new_post_url != ''
      run: |
        curl -X POST "https://${{ secrets.MASTODON_INSTANCE_URL }}/api/v1/statuses" \
        -H "Authorization: Bearer ${{ secrets.MASTODON_ACCESS_TOKEN }}" \
        -d "visibility=unlisted&status=New blog post: ${{ env.new_post_url }}"