name: Post New Blog Post to Mastodon

on:
  push:
    paths:
      - _posts/**

jobs:
  post-to-mastodon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Find new blog post
      id: new_post
      run: |
        NEW_POST=$(git diff-tree --no-commit-id --name-only -r HEAD | grep _posts/ | tail -n 1)
        POST_NAME=$(basename "$NEW_POST" .md)
        DATE_PART=$(echo "$POST_NAME" | cut -d'-' -f1-3 | tr '-' '/')
        SLUG_PART=$(echo "$POST_NAME" | cut -d'-' -f4-)
        POST_URL="https://khevans.com/$DATE_PART/$SLUG_PART/"
        echo "new_post_url=$POST_URL" >> $GITHUB_ENV

    - name: Post to Mastodon
      if: env.new_post_url != ''
      run: |
        curl -X POST "https://${{ secrets.MASTODON_INSTANCE_URL }}/api/v1/statuses" \
        -H "Authorization: Bearer ${{ secrets.MASTODON_ACCESS_TOKEN }}" \
        -d "status=New blog post: ${{ env.new_post_url }}"
